routes/web.php
<?php

use App\Contracts\Hammer;
use App\Contracts\Nail;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PostController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Route;
use Teto\HTTP\AcceptLanguage;
use App\Http\Controllers\FormController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('welcome/{lang?}', function ($lang = null) {

    /*
    $languages = ['tr', 'en'];
    if (!in_array($lang, $languages)) {
        return "Geçersiz bir dil belirttiniz.";
    }
    */

    // basit bir karşılama sayfası hazırlayacağız.
    // bu karşılama sayfası Türkçe ve İngilizce seçeneklerle
    // hizmet verecek. Her iki dil için metin değerlerini
    // barındıran birer dizi oluşturacağız. Tercih edilen
    // dile göre ilgili dizinin elemanları ile çıktıyı oluşturacağız.

    $translations = [
        'tr' => [
            'welcome' => "Hoşgeldiniz",
            'intro' => "Biz en iyisiyiz",
            'headline' => "Diğerlerini boşverin",
            'outro' => "Daha fazlası için takip etmeye devam edin",
        ],
        'en' => [
            'welcome' => "Welcome",
            'intro' => "We're the best",
            'headline' => "Ignore the rest",
            'outro' => "Keep following for more",
        ],
        'es' => [
            'welcome' => "Bienvenido",
            'intro' => "Somos los mejores",
            'headline' => "Ignorar el resto",
            'outro' => "Sigue siguiendo para más",
        ],
        'fr' => [
            'welcome' => "Accueillir",
            'intro' => "Nous sommes les meilleurs",
            'headline' => "Ignorer le reste",
            'outro' => "Continuez à suivre pour en savoir plus",
        ],
    ];


    // Adres çubuğundan dil gelmediyse, request header'larındaki
    // Accept-Language dil dizisinin içinde var mı diye kontrol edilecek
    // Varsa o dil kullanılacak, yoksa İngilizce kullanılacak.
    // "factor" önemli değil, sırası önemli.
    // explode() ile belirli karaktere göre ayrım sağlayabiliriz.

    // Örneğin; Accept-Language: tr-TR,tr;q=0.9 ise ve /welcome şeklinde ziyaret edilmişse
    // site Türkçe dilinde gösterilmeli.
    // Örneğin; Accept-Language: jp... ise ve /welcome şeklinde ziyaret edilmişse
    // sitemizde bu dil olmadığı için site İngilizce dilinde gösterilmeli.


    /*
    $prefferedLanguage = substr($request->header('accept-language'), 0, 2);
    // dd($prefferedLanguage);

    if ($lang == null) {
        $lang = $prefferedLanguage;
    }
    */

    // 1. 'Accept-Language' headerına eriş
    // dd($request->header('accept-language'));
    // 2. kullanıcının istediği dillerin listesi olacak şekilde düzenle
    // Accept-Language: en-US,en;q=0.8,tr-TR,tr;q=0.9 --> [en,tr]
    // 3. bu listedeki herhangi bir eleman dil listesinde bulunuyorsa lang
    // değerine eşitle
    // 4. listenin devamını kontrol etme

    // Daha sonra Middleware olarak kullanılacak
    if ($lang == null) {
        $lang = 'en';
        foreach(AcceptLanguage::get() as $language) {
            if (in_array($language['language'], array_keys($translations))) {
                $lang = $language['language'];
                break;
            }
        }
    }

    // Prensipler; Inversion of Control, Dependency Inversion Principle
    // Desen/Pattern; Dependency Injection
    // Çatı/Framework; IoC Container

    // if (!isset($translations[$lang])) {
    //    return "İstediğiniz dil bulunmuyor";
    // }

    // dump($translations[$lang]);
    // dump n die
    // dd();

    return view('landing', [
        'lang' => $lang,
        'translations' => $translations[$lang],
        'languages' => array_keys($translations),
    ]);

})->name('landing');

Route::get('set-color/{color}', function ($color) {
    return redirect()->back()->withCookie('color', $color);
});

Route::get('story', [FormController::class, 'show'])->name('story.show');

Route::post('story', [FormController::class, 'handle'])->name('story.handle');

Route::match(['get', 'post'], 'hem-get-hem-post', function () {
    dd("Burası hem GET hem POST ile çalışıyor");
});

Route::any('tum-methodlar-icin', function () {
    dd('Burası tüm method lar için çalışıyor');
});

// index -> listeleme
// create -> ekleme formunu gösterme
// store -> eklemenin yapılacağı yer
// show  -> görüntüleme
// edit -> düzenleme formunu gösterme
// update -> güncellemenin yapılacağı yer
// destroy -> silinmenin yapılacağı yer
Route::resource('posts', PostController::class);

Route::resource('categories', CategoryController::class);

Route::get('app', function() {
    dd(app());
});

Route::get(
    'carpenter',
    function (Hammer $hammer, Nail $nail) {
        // bana gelen IzeltasCekic mi KorkmazCekic mi belli değil
        $hammer->nailing($nail, "sol üst");
        $hammer->nailing($nail, "sağ üst");
    }
);

// Create => create, store
// Read => index, show
// Update => edit, update
// Delete => destroy

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

$post->category;

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $posts = Post::query();

        if ($request->has('category_id')) {
            $posts->where('category_id', $request->get('category_id'));
        }

        $posts = $posts->get();

        // compact('var1', 'var2') ---> ['var1' => $var1, 'var2' => $var2]
        // farklı avantajları/dezavantajları var

        return view('post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::all();
        return view('post.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'category_id' => 'required|exists:categories,id',
            'title' => 'required|string|max:250',
            'content' => 'nullable|string',
        ]);
        
        $post = new Post;

        $post->category()->associate($request->input('category_id'));
        $post->title = $request->input('title');
        $post->content = $request->input('content');

        $post->save();

        return redirect()->route('posts.show', $post);
    }

    /**
     * Display the specified resource.
     */
    public function show(Post $post)
    {
        return view('post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Post $post)
    {
        $categories = Category::all();

        return view('post.edit', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Post $post)
    {
        $request->validate([
            'category_id' => 'required|exists:categories,id',
            'title' => 'required|string|max:250',
            'content' => 'nullable|string',
        ]);

        $post->category()->associate($request->input('category_id'));
        $post->title = $request->input('title');
        $post->content = $request->input('content');

        $post->save();

        return redirect()->route('posts.show', $post);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Post $post)
    {
        $post->delete();

        return redirect()->route('posts.index');
    }
}

resources/views/post/create.blade.php
@if ($errors->any())
    <p>Bir hata gerçekleşti.</p>
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
@endif

<form method="POST" action="{{ route('posts.store') }}">
    @csrf
    <label for="slcCategory">Kategori</label>
    <br>
    <select name="category_id" id="slcCategory">
        @foreach ($categories as $category)
            <option value="{{ $category->id }}">{{ $category->name }}</option>
        @endforeach
    </select>
    <br>
    <label for="inpTitle">Başlık</label>
    <br>
    <input type="text" value="{{ old('title') }}" name="title" id="inpTitle" />
    <br>
    <label for="inpContent">İçerik</label>
    <br>
    <textarea name="content" id="inpContent">{{ old('content') }}</textarea>
    <br>
    <button type="submit">Ekle</button>
    <a href="{{ route('posts.index') }}">Geri Dön</a>
</form>

resources/views/post/edit.blade.php
@if ($errors->any())
    <p>Bir hata gerçekleşti.</p>
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
@endif

<form method="POST" action="{{ route('posts.update', $post) }}">
    @csrf
    @method('PUT')
    <label for="slcCategory">Kategori</label>
    <br>
    <select name="category_id" id="slcCategory">
        @foreach ($categories as $category)
            <option
                @if($post->category_id == $category->id )
                    selected
                @endif
                value="{{ $category->id }}">
                {{ $category->name }}
            </option>
        @endforeach
    </select>
    <br>
    <label for="inpTitle">Başlık</label>
    <br>
    <input type="text" value="{{ $errors->any() ? old('title') : $post->title }}" name="title" id="inpTitle" />
    <br>
    <label for="inpContent">İçerik</label>
    <br>
    <textarea name="content" id="inpContent">{{ $errors->any() ? old('content') : $post->content }}</textarea>
    <br>
    <button type="submit">Güncelle</button>
    <a href="{{ route('posts.show', $post) }}">Geri Dön</a>
</form>

resources/views/post/index.blade.php
<p>
    <a href="{{ route('posts.create') }}">Yeni Yazı Ekle</a>
</p>
<ul>
    @forelse ($posts as $post)
        <li>
            <a href="{{ route('posts.show', $post) }}">
                {{ $post->title }}
            </a>
        </li>
    @empty
        <li>
            Herhangi bir yazı bulunamadı
        </li>
    @endforelse
</ul>

resources/views/post/show.blade.php
<h1>{{ $post->title }}</h1>
<p>
    Kategori:
    <a href="{{ route('categories.show', $post->category) }}">
        {{ $post->category->name }}
    </a>
</p>
<p>
    {{ $post->content }}
</p>
<p>
    <small>{{ $post->created_at->diffForHumans() }}</small>
</p>
<p>
    <a href="{{ route('posts.edit', $post) }}">Düzenle</a>
    <form method="POST" action="{{ route('posts.destroy', $post) }}">
        @csrf
        @method('DELETE')
        <button type="submit">Sil</button>
    </form>
    <a href="{{ route('posts.index') }}">Geri Dön</a>
</p>