routes/web.php
<?php

use App\Contracts\Hammer;
use App\Contracts\Nail;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\PostController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Route;
use Teto\HTTP\AcceptLanguage;
use App\Http\Controllers\FormController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('welcome/{lang?}', function ($lang = null) {

    /*
    $languages = ['tr', 'en'];
    if (!in_array($lang, $languages)) {
        return "Geçersiz bir dil belirttiniz.";
    }
    */

    // basit bir karşılama sayfası hazırlayacağız.
    // bu karşılama sayfası Türkçe ve İngilizce seçeneklerle
    // hizmet verecek. Her iki dil için metin değerlerini
    // barındıran birer dizi oluşturacağız. Tercih edilen
    // dile göre ilgili dizinin elemanları ile çıktıyı oluşturacağız.

    $translations = [
        'tr' => [
            'welcome' => "Hoşgeldiniz",
            'intro' => "Biz en iyisiyiz",
            'headline' => "Diğerlerini boşverin",
            'outro' => "Daha fazlası için takip etmeye devam edin",
        ],
        'en' => [
            'welcome' => "Welcome",
            'intro' => "We're the best",
            'headline' => "Ignore the rest",
            'outro' => "Keep following for more",
        ],
        'es' => [
            'welcome' => "Bienvenido",
            'intro' => "Somos los mejores",
            'headline' => "Ignorar el resto",
            'outro' => "Sigue siguiendo para más",
        ],
        'fr' => [
            'welcome' => "Accueillir",
            'intro' => "Nous sommes les meilleurs",
            'headline' => "Ignorer le reste",
            'outro' => "Continuez à suivre pour en savoir plus",
        ],
    ];


    // Adres çubuğundan dil gelmediyse, request header'larındaki
    // Accept-Language dil dizisinin içinde var mı diye kontrol edilecek
    // Varsa o dil kullanılacak, yoksa İngilizce kullanılacak.
    // "factor" önemli değil, sırası önemli.
    // explode() ile belirli karaktere göre ayrım sağlayabiliriz.

    // Örneğin; Accept-Language: tr-TR,tr;q=0.9 ise ve /welcome şeklinde ziyaret edilmişse
    // site Türkçe dilinde gösterilmeli.
    // Örneğin; Accept-Language: jp... ise ve /welcome şeklinde ziyaret edilmişse
    // sitemizde bu dil olmadığı için site İngilizce dilinde gösterilmeli.


    /*
    $prefferedLanguage = substr($request->header('accept-language'), 0, 2);
    // dd($prefferedLanguage);

    if ($lang == null) {
        $lang = $prefferedLanguage;
    }
    */

    // 1. 'Accept-Language' headerına eriş
    // dd($request->header('accept-language'));
    // 2. kullanıcının istediği dillerin listesi olacak şekilde düzenle
    // Accept-Language: en-US,en;q=0.8,tr-TR,tr;q=0.9 --> [en,tr]
    // 3. bu listedeki herhangi bir eleman dil listesinde bulunuyorsa lang
    // değerine eşitle
    // 4. listenin devamını kontrol etme

    // Daha sonra Middleware olarak kullanılacak
    if ($lang == null) {
        $lang = 'en';
        foreach(AcceptLanguage::get() as $language) {
            if (in_array($language['language'], array_keys($translations))) {
                $lang = $language['language'];
                break;
            }
        }
    }

    // Prensipler; Inversion of Control, Dependency Inversion Principle
    // Desen/Pattern; Dependency Injection
    // Çatı/Framework; IoC Container

    // if (!isset($translations[$lang])) {
    //    return "İstediğiniz dil bulunmuyor";
    // }

    // dump($translations[$lang]);
    // dump n die
    // dd();

    return view('landing', [
        'lang' => $lang,
        'translations' => $translations[$lang],
        'languages' => array_keys($translations),
    ]);

})->name('landing');

Route::get('set-color/{color}', function ($color) {
    return redirect()->back()->withCookie('color', $color);
});

Route::get('story', [FormController::class, 'show'])->name('story.show');

Route::post('story', [FormController::class, 'handle'])->name('story.handle');

Route::match(['get', 'post'], 'hem-get-hem-post', function () {
    dd("Burası hem GET hem POST ile çalışıyor");
});

Route::any('tum-methodlar-icin', function () {
    dd('Burası tüm method lar için çalışıyor');
});

// index -> listeleme
// create -> ekleme formunu gösterme
// store -> eklemenin yapılacağı yer
// show  -> görüntüleme
// edit -> düzenleme formunu gösterme
// update -> güncellemenin yapılacağı yer
// destroy -> silinmenin yapılacağı yer
Route::resource('posts', PostController::class);

Route::resource('categories', CategoryController::class);

Route::get('app', function() {
    dd(app());
});

Route::get(
    'carpenter',
    function (Hammer $hammer, Nail $nail) {
        // bana gelen IzeltasCekic mi KorkmazCekic mi belli değil
        $hammer->nailing($nail, "sol üst");
        $hammer->nailing($nail, "sağ üst");
    }
);

// Create => create, store
// Read => index, show
// Update => edit, update
// Delete => destroy

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $categories = Category::query();
        $order = $request->get('order');

        if ($order === "desc") {
            $categories->orderByDesc('name');
        } else {
            $categories->orderBy('name');
        }

        $categories = $categories->get();

        return view('category.index', compact('categories', 'order'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:250|unique:categories',
        ]);

        $category = new Category;
        $category->name = $request->input('name');
        $category->save();

        return redirect()->route('categories.show', $category);
    }

    /**
     * Display the specified resource.
     */
    public function show(Category $category)
    {
        $posts = $category->posts()->latest()->take(3)->get();
        
        return view('category.show', compact('category', 'posts'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Category $category)
    {
        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'name' => 'required|string|max:250|unique:categories',
        ]);

        $category->name = $request->input('name');
        $category->save();

        return redirect()->route('categories.show', $category);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->route('categories.index');
    }
}

resources/views/category/create.blade.php
@if ($errors->any())
    <p>Bir hata gerçekleşti.</p>
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
@endif

<form method="POST" action="{{ route('categories.store') }}">
    @csrf
    <label for="inpName">İsim</label>
    <br>
    <input type="text" value="{{ old('name') }}" name="name" id="inpName" />
    <br>
    <button type="submit">Ekle</button>
    <a href="{{ route('categories.index') }}">Geri Dön</a>
</form>

resources/views/category/edit.blade.php
@if ($errors->any())
    <p>Bir hata gerçekleşti.</p>
    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
@endif

<form method="POST" action="{{ route('categories.update', $category) }}">
    @csrf
    @method('PUT')
    <label for="inpName">Başlık</label>
    <br>
    <input type="text" value="{{ $errors->any() ? old('name') : $category->name }}" name="name" id="inpName" />
    <br>
    <button type="submit">Güncelle</button>
    <a href="{{ route('categories.show', $category) }}">Geri Dön</a>
</form>

resources/views/category/index.blade.php
<p>
    <a href="{{ route('categories.create') }}">Yeni Kategori Ekle</a>
</p>
<br>
<form method="GET">
    <select name="order">
        <option value="asc">A-Z</option>
        <option @if($order === 'desc') selected @endif value="desc">Z-A</option>
    </select>
    <button type="submit">Sırala</button>
</form>
<ul>
    @foreach ($categories as $category)
        <li>
            <a href="{{ route('categories.show', $category) }}">
                {{ $category->name }}
            </a>
        </li>
    @endforeach
</ul>

resources/views/category/show.blade.php
<h1>{{ $category->name }}</h1>
<p>
    <small>{{ $category->created_at->diffForHumans() }}</small>
</p>
<ul>
    @foreach($posts as $post)
        <li>
            <a href="{{ route('posts.show', $post) }}">
                {{ $post->title }}
            </a>
        </li>
    @endforeach
</ul>
<p>
    <a href="{{ route('posts.index', ['category_id' => $category->id]) }}">Tüm yazıları gör</a>
</p>
<p>
    <a href="{{ route('categories.edit', $category) }}">Düzenle</a>
    <form method="POST" action="{{ route('categories.destroy', $category) }}">
        @csrf
        @method('DELETE')
        <button type="submit">Sil</button>
    </form>
    <a href="{{ route('categories.index') }}">Geri Dön</a>
</p>